apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  - name: "9000"
    port: 9000
    targetPort: 9000
  selector:
    io.kompose.service: app
status:
  loadBalancer: {}
