apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: odm-db-data
  name: odm-db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
